### ISSUE TITLE
Add blogging support

### ISSUE THREAD

**Issue by paulpopus** [localgovdrupal/docs#10]
Add blogging support to the documentation repo

EDIT:
Blogging should sit on a separate platform from the docs. We could still have our own repo or we can use a service.

I know that [dev.to](https://dev.to/) and [hashnode](https://hashnode.com/) are recommended, my only objection would be to medium.

**Comment by paulpopus** [comment]
Going to reopen this.

@finnlewis If we have an email I could use to set up an account on a platform I'm happy to get this started.

**Comment by finnlewis** [comment]
Good call @paulpopus 

I think individual authors should write their own blog posts, but collected in a single place if possible. Is it possible to set up a project blog account somewhere with multiple authors? 

I like the look of hashnode, but I'm not sure if this should be just developer focussed. 

@willguv  - any thoughts on what kind of blogging woul dbe good for starters? 

On the email address front, maybe we should set up email addresses like blog@localgovdrupal.org if needed.

**Comment by willguv** [comment]
Yes definitely good call @paulpopus 

CLG would like me to write a project update ASAP, finishing off the Alpha and setting out next steps. It's blocked by agreeing a new lead council, but that will happen imminently

I'd also like to move all the croydon.digital blog posts to this new home, to keep everything in one place. Also I'm not sure if c.d is continuing long term

Once we have our own blog platform, think the sky is the limit. I'd like to post after most product group sessions, and would be good to get updates from our emerging communities of practice eg accessibility

I can check on setting up localgovdrupal.org email addresses - should be straightforward. I was planning to set up hello@ as a first point of contact for enquiries, and can do others. Please let me know what you think
