### ISSUE TITLE
Fix 2 broken links on docs pages

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/docs#105]
ignoring all those in /blog

1) https://docs.localgovdrupal.org/devs/getting-started/
'Jump to Working with Lando for more information' under 'Development Setup'

2) https://docs.localgovdrupal.org/devs/theme/old-localgov-theme.html
'Jump to documentation' under Skeleton theme

**Comment by msayoung** [comment]
Done, and deployed.

**Comment by MichaelDCR** [comment]
:)
