### ISSUE TITLE
Documentation: phase 1

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/docs#125]
A section of the docs site, for now.

- [x] Microsite proposition
- [ ] Glossary of terms
- [ ] General guidance 
- [ ] Create a microsite
- [ ] Microsite configuration (site design etc)

We want something, but doesn't need to be too detailed at present as we'll need to keep it up to date.

**Comment by finnlewis** [comment]
Note: we can start this in a Google doc and move to the https://docs.localgovdrupal.org/ for initial place to live

**Comment by msayoung** [comment]
https://docs.google.com/document/d/1htCTAwfc72qs3RBx9dH-NUdfgBg23Ftr0yueBUyejac/edit#heading=h.7bfnoju4wx9j

**Comment by finnlewis** [comment]
Amazing start, thanks @msayoung !

**Comment by msayoung** [comment]
https://docs.google.com/document/d/1htCTAwfc72qs3RBx9dH-NUdfgBg23Ftr0yueBUyejac/edit#heading=h.n3xgagro1syi
