### ISSUE TITLE
Analytics on Docs pages

### ISSUE THREAD

**Issue by MichaelDCR** [localgovdrupal/docs#148]
Can we add Google Analytics to the docs?

I found supposed method for Vuepress:
https://v2.vuepress.vuejs.org/reference/plugin/google-analytics.html
https://github.com/vuejs/vuepress/issues/2713
That doesn't provide any cookie consent, but I think we can be relaxed around that frankly. 

The GA4 measurement ID is:  G-ETT82J89DV

**Comment by stephen-cox** [comment]
@MichaelDCR There's PR #155 adding gtag.js to the header along with the ID given above. The test URL for this is: https://deploy-preview-155--inspiring-euclid-d918c8.netlify.app/

Does this load GA correctly? If so the PR can be merged
