### ISSUE TITLE
Removing the project template version control

### ISSUE THREAD

**Issue by iam-jam** [localgovdrupal/docs#15]
Once `composer create-project` has completed users are prompted to remove version control, unless you are contributing to the project then you'll always want to do so we should recommend using the `--remove-vcs` with `create-project` so the users isn't prompted.

**Comment by finnlewis** [comment]
Thanks @iam-jam 

Like this? 

https://github.com/localgovdrupal/docs/pull/16

**Comment by finnlewis** [comment]
Feel free to make commits onto a new branch and create pull requests.

Usually our branches are named like 
 - featre/[issue-number]-[description])

For example, for this issue I created the branch  /feature/15-remove-vcs
