### ISSUE TITLE
Accessibility figcaption coverage

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/docs#19]
Extend images test section to include coverage of `<figure>` and `<figcaption>`

**Comment by msayoung** [comment]
@danchamp - do you know if this is still an issue, and if so can you give some more information?

**Comment by danchamp** [comment]
It's only an issue by omission, I know the elements aren't used much but felt we should cover them in guidance.

Good summaries at [HTML5 Doctor](http://html5doctor.com/the-figure-figcaption-elements/) and [thoughtbot](https://thoughtbot.com/blog/alt-vs-figcaption).

I'm happy to leave this assigned to me - I have some free time approaching and intend to spend some of it on LGD accessibility - but equally happy if you or anyone else has the time/will to pick it up.

**Comment by keelanfh** [comment]
@msayoung

**Comment by danchamp** [comment]
Closing, plenty of reference material online covering this.
