### ISSUE TITLE
Fix security issues

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/docs#190]
From https://github.com/localgovdrupal/docs/security/dependabot

![image](https://github.com/localgovdrupal/docs/assets/7189914/c54176a7-8537-4b06-8f53-864986f19a3e)

**Comment by millnut** [comment]
I've upgraded this locally to v2, there is still a lot of work to do on the theme as vuepress has moved from stylus to sass as well as the vue components we extend no longer exist.

Would be good to know how to get this on a test area so I can test with AlgoliaSearch as well as that has had quite an extensive re-write

**Comment by stephen-cox** [comment]
If you create a PR then the changes should be automatically get deployed to a test URL in Netlify.

**Comment by millnut** [comment]
Excellent thanks @stephen-cox I'm just tweaking the theme to match the new website design. Will create a PR once that is all complete
