### ISSUE TITLE
Site title/logo is obscured on some screen widths

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/docs#194]
![image](https://github.com/localgovdrupal/docs/assets/19519457/b0d680d6-ab33-4ead-8eea-59ddba6ca3d1)

Seems to happen at viewport widths between 1220-1480px

**Comment by stephen-cox** [comment]
We have too many top-level menu items. If we want to keep them all then they should be in a drop-down rather than having them all listed along the top.
