### ISSUE TITLE
Replacement URL for linked Brighton & Hove Pattern Library

### ISSUE THREAD

**Issue by jpoesen** [localgovdrupal/docs#259]
The "Pattern Library created by Brighton & Hove City Council"  link on https://docs.localgovdrupal.org/content/patterns.html leads to a 403 Permission Denied page.

It looks like the new url is: https://design.brighton-hove.gov.uk/website-pattern-library.php?p=service-icons

Could someone confirm this is what we want to link to?

**Comment by andybroomfield** [comment]
@jpoesen I wouldn't consider that current at the moment and it's probabbly best removed.

**Comment by jpoesen** [comment]
Thanks @andybroomfield. 

Should someone else weigh in as well or are you confident and shall I just go in and remove that link?

**Comment by andybroomfield** [comment]
Thats the old BHCC pattern and at some point it is being removed from our site pending replacement.
The information on that link is quite far out of date from our sites perspective.

**Comment by jpoesen** [comment]
Ok, understood. 
Will remove.

Thanks Andy!

**Comment by finnlewis** [comment]
Looks like we fixed this one, thanks folks!
