### ISSUE TITLE
Document subsites

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/docs#54]
We need some documentation for subsites. 

- [x] Intro
- [x] Content designers
- [ ] Technical

**Comment by msayoung** [comment]
I've made a start on the subsite documentation (for content editors) here: https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/content/features/subsites.html#when-to-use-a-subsite 

@willguv does that information seem correct ?

**Comment by willguv** [comment]
@msayoung it looks correct from what I know

There's a few Lambeth originated features that I'm not as familiar with (eg primary and secondary banners)

I think publish for now, and we can revisit before the end of Beta

Cheers for sorting this out!

**Comment by msayoung** [comment]
There's some draft technical content here also: 

- https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/devs/features/subsites.html  

There's some bits I still need to fill in.
