### ISSUE TITLE
Update doc site IA

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/docs#65]
As per @MichaelDCR 's new IA  for the docs site. 

For now we want top level items for:

1. Developers
2. Content designers
3. Theme (as current)
4. Contributing (as current)
5. Accessibility (as current)
6. Github (as current)

The Developers section will include
1. Getting started (as current)
2. General config
3. Features ( intro and technical info for each of the features )
4. Testing
5. Issues

The Content Designers section will include
1. Introduction
2. Features ( intro and how-to for each of the features)

After we have the new "shop window" there may be further changes.

**Comment by msayoung** [comment]
@MichaelDCR 
You can preview the changes I've made here: https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/
Question 1. Does that new IA work for now? 


There is also the start of some documentation for subsites in there too:
https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/content/features/subsites.htm

**Comment by msayoung** [comment]
Also, are we going to have an overview of all the features somewhere more top level?

**Comment by MichaelDCR** [comment]
@msayoung 
Hi Maria

Q.1 Yes! Until we get the new site up[ and can remove the Blog

Subsites looks good. 

In the Content Designers > Features should we rename Services as 'Service pages'. Also is it possible / a desirable for me to make minor edits myself. For example renaming 'Guide' as 'Guide pages' or 'Step by step' as Step by step pages' for clarity. 

We should have an overview of the features in the Features page on the main site, but that will be salesy, so if I get what you are saying then yes that seems like a good idea.

**Comment by msayoung** [comment]
I think we need to be careful about mixing up Services as a feature (bundling up various mini-features) and the content type called Service Page (which is one of the content types in the feature). 

In the case of Guides and Step-by-steps it maybe makes more sense, but they also come with on-page menus etc. 

also, while I remember @danchamp and I were trying to find some consistency in the docs about capitalisation, and ended up going for (against our personal preference) Service Page when its referring to the proper name of a thing (like a content type). would value your input in to this. 

I'm happy for you to make edits. would you like me to give you a quick tour of how?

**Comment by MichaelDCR** [comment]
Ah yes, that wouldn't work. We do need a higher level explanation of what 'Services' are then, as per the overview you mentioned.  

Perhaps on this page https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/content/features/ and the one for Devs https://deploy-preview-62--trusting-noyce-aebebc.netlify.app/devs/features/

'Guide' and Step by step' can have another meaning when looking at docs so definitely need to change those. 

I prefer to capitalise both parts of a name so upvote 'Alert Banners' and 'Step by Step'

Yes to a tour would be great if we can do it quickly tomorrow during our meeting - just need to be pointed at the correct files I think.
